-- ============================================================
-- Bynarical Worktime — Supabase 스키마 + RLS
-- 사용법: Supabase 대시보드 → SQL Editor → New query → 전체 붙여넣고 Run
-- (여러 번 실행해도 안전하도록 작성됨)
-- ============================================================

-- ---------- 1) 프로필 (auth.users 1:1) ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  emp_no text,
  hire_date date,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

-- ---------- 2) 근무지 (전역, 관리자 관리) ----------
create table if not exists public.workplaces (
  id text primary key,
  name text not null,
  lat double precision not null,
  lng double precision not null,
  radius integer not null default 150
);

-- ---------- 3) 앱 정책 (단일 행) ----------
create table if not exists public.app_settings (
  id integer primary key default 1,
  work_policy jsonb,
  leave_policy jsonb,
  updated_at timestamptz default now(),
  constraint app_settings_singleton check (id = 1)
);

-- ---------- 4) 근태 기록 ----------
create table if not exists public.records (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  planned_start text,
  check_in timestamptz,
  check_out timestamptz,
  type text not null default 'WORK',
  workplace_id text,
  workplace_name text,
  in_lat double precision,
  in_lng double precision,
  in_verified boolean,
  out_lat double precision,
  out_lng double precision,
  out_verified boolean,
  note text,
  hash text,
  prev_hash text,
  updated_at timestamptz default now(),
  unique (user_id, date)
);

-- ---------- 5) 연차 ----------
create table if not exists public.leaves (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  hours integer not null,
  segment text not null,
  start_time text,
  end_time text,
  reason text,
  status text not null default 'REQUESTED',
  requested_at timestamptz default now(),
  decided_at timestamptz,
  decided_by text,
  decision_note text,
  hash text,
  prev_hash text
);

-- ---------- 6) 주간 확인(전자서명) ----------
create table if not exists public.confirmations (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  week_start date not null,
  week_end date not null,
  signature text,
  total_worked_minutes integer default 0,
  summary_hash text,
  hash text,
  prev_hash text,
  confirmed_at timestamptz default now(),
  unique (user_id, week_start)
);

-- ---------- 7) 연차 수동 조정 ----------
create table if not exists public.leave_adjustments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  hours numeric not null,
  note text,
  created_by uuid,
  at timestamptz default now()
);

-- ============================================================
-- 헬퍼 함수: 현재 사용자가 관리자인지 (RLS 재귀 방지 위해 SECURITY DEFINER)
-- ============================================================
create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select coalesce((select is_admin from public.profiles where id = auth.uid()), false);
$$;

-- 이름 → 로그인 이메일 조회 (직원은 이름+비밀번호로 로그인).
-- 정확히 1명일 때만 이메일 반환(동명이인/없음 → null). anon도 호출 가능해야 로그인 화면에서 사용.
create or replace function public.login_email_for_name(p_name text)
returns text
language plpgsql
security definer
stable
set search_path = public, auth
as $$
declare c int; e text;
begin
  select count(*) into c from public.profiles where trim(name) = trim(p_name);
  if c <> 1 then return null; end if;
  select u.email into e
    from auth.users u join public.profiles pr on pr.id = u.id
    where trim(pr.name) = trim(p_name);
  return e;
end;
$$;
grant execute on function public.login_email_for_name(text) to anon, authenticated;

-- ============================================================
-- 가입 시 프로필 자동 생성 (회원가입 메타데이터에서 이름/사번 등 추출)
-- ============================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, emp_no, hire_date, is_admin)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    nullif(new.raw_user_meta_data->>'emp_no', ''),
    nullif(new.raw_user_meta_data->>'hire_date', '')::date,
    coalesce((new.raw_user_meta_data->>'is_admin')::boolean, false)
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- RLS 활성화
-- ============================================================
alter table public.profiles enable row level security;
alter table public.workplaces enable row level security;
alter table public.app_settings enable row level security;
alter table public.records enable row level security;
alter table public.leaves enable row level security;
alter table public.confirmations enable row level security;
alter table public.leave_adjustments enable row level security;

-- 정책 재실행 안전: 기존 정책 제거 후 생성
do $$
declare r record;
begin
  for r in
    select policyname, tablename from pg_policies
    where schemaname = 'public'
      and tablename in ('profiles','workplaces','app_settings','records','leaves','confirmations','leave_adjustments')
  loop
    execute format('drop policy if exists %I on public.%I', r.policyname, r.tablename);
  end loop;
end $$;

-- profiles: 본인/관리자 조회, 본인 생성/수정, 관리자 수정
create policy profiles_select on public.profiles for select
  using (id = auth.uid() or public.is_admin());
create policy profiles_insert on public.profiles for insert
  with check (id = auth.uid());
create policy profiles_update on public.profiles for update
  using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());

-- records: 본인 전체 권한 + 관리자 조회
create policy records_owner_all on public.records for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy records_admin_select on public.records for select
  using (public.is_admin());

-- leaves: 본인 전체 권한 + 관리자 조회/수정(승인)
create policy leaves_owner_all on public.leaves for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy leaves_admin_select on public.leaves for select
  using (public.is_admin());
create policy leaves_admin_update on public.leaves for update
  using (public.is_admin()) with check (public.is_admin());

-- confirmations: 본인 전체 권한 + 관리자 조회
create policy confirmations_owner_all on public.confirmations for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy confirmations_admin_select on public.confirmations for select
  using (public.is_admin());

-- workplaces: 로그인 사용자 조회, 관리자만 쓰기
create policy workplaces_select on public.workplaces for select
  using (auth.uid() is not null);
create policy workplaces_admin_write on public.workplaces for all
  using (public.is_admin()) with check (public.is_admin());

-- app_settings: 로그인 사용자 조회, 관리자만 쓰기
create policy settings_select on public.app_settings for select
  using (auth.uid() is not null);
create policy settings_admin_write on public.app_settings for all
  using (public.is_admin()) with check (public.is_admin());

-- leave_adjustments: 본인/관리자 조회, 관리자만 쓰기
create policy adj_select on public.leave_adjustments for select
  using (user_id = auth.uid() or public.is_admin());
create policy adj_admin_write on public.leave_adjustments for all
  using (public.is_admin()) with check (public.is_admin());

-- ============================================================
-- 기본 데이터 (선택)
-- ============================================================
insert into public.app_settings (id) values (1) on conflict (id) do nothing;
insert into public.workplaces (id, name, lat, lng, radius)
  values ('wp_default', '서울창업허브 엠플러스', 37.5613474, 126.8288372, 150)
  on conflict (id) do nothing;

-- ============================================================
-- 첫 관리자 지정: 본인이 가입한 뒤 아래 한 줄을 실행하세요.
--   update public.profiles set is_admin = true where emp_no = 'admin';
-- (또는 이메일 기준)
--   update public.profiles set is_admin = true where id =
--     (select id from auth.users where email = 'you@company.com');
-- ============================================================
